# Generated by Django 4.2 on 2023-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('number_courses', models.IntegerField(blank=True)),
                ('email_akk', models.CharField(max_length=200)),
                ('arrival_days', models.IntegerField(blank=True)),
                ('empty_course', models.IntegerField(blank=True)),
                ('busy_courses', models.IntegerField(blank=True)),
            ],
        ),
    ]
