# Generated by Django 4.2 on 2023-04-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
