# Generated by Django 4.2 on 2023-04-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_frist_name_contact_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_num',
            new_name='phone',
        ),
    ]
